version: "3.9"

services:
  site:
    image: "${DOCKER_IMAGE}:latest"
    container_name: site
    restart: unless-stopped
    expose:
      - "${CONTAINER_PORT}"  # Контейнер слушает порт, но не проброшен наружу
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    networks:
      - web
    depends_on:
      - site

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;"
    networks:
      - web

networks:
  web:
    driver: bridge